### ISSUE TITLE
No valid profile for WordPress during site-install

### ISSUE THREAD

**Issue by masonjames** [uberhacker/pantheon-local-drupal-development#6]
Hiya!

First off, this is awesome.  Great work!

I was attempting to use this with a few WordPress sites we have on Pantheon, but when I attempt to perform site-install I'm unsure of what 'profile' to use.  I made a few guesses, but they all came up invalid and I couldn't find any documentation on this.  Is there a way around this for WordPress sites?

Thanks again!

**Comment by uberhacker** [comment]
Hey Mason,
Glad you like it.  When I originally created this project, I only had Drupal in mind and tested it in that specific working environment but I can certainly look into making it work for WordPress as well.  I just don't work on WordPress sites much since most of my clients use Drupal.  Thanks for the feedback!

**Comment by masonjames** [comment]
Your documentation writeup is fantastic. I realized WP wasn't the goal for this project. I'm toying with a bash script I found for WordPress here:
https://gist.github.com/emirpprime/37ef1f355ec5a7ecbb8f

I may tinker with that a bit and see if I can hack something together that would apply to WordPress - regardless though good stuff. I'll close this issue since out. Thanks again.
